dist: trusty
language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "francesco1997"
    token:
      secure: "FI5OMeVh08L115aXNFlueUKBc83lxpJn769/mXzcFM9dhUHJHup93O4V53MzrlxBYj5LPrMiQykFAR1yHDkxcjEct2pMo7gRx6D6csdawSHNf4yUGSYX3hrBOIjOKwB+ZU6yAYf1rWkcAUzXY7o2E7io9Si5y6onojigj/NmtQHomvvqipcLBCCZfjTZSFZqR8NBOxmzI5gdho/MVBx1GfhQ5wYA9A4Pp6rPiAIVY6a3LI99faOPOhpI4KCGnXecd1RlplIm5/TUJOVeUkCb/wqUhxjbh3L5oXFiHzJRzst50LYO/6Jzrxy8v0qESrhubofx65JaD3PJo76iayRK0k2GAR9ycX7Xwusg8dIMwppdxwTu2aEkPjRYoBfAGCBsxpm5QYWSfbfB0Zj48CwrjO1URB5qpjFngY42A/YRFIBty0DzJvB+8DO81PMwYXoW6O21zOC9GR4hKHGM9Kl0f+HhQeo6BcZId5RQYz9nKy4U/ZSVyB1rXkyM2bbgLiuybBiixjSd8WEuvcI1YMYSO2hnGG5bFvOVBRo+gkq1i3ar2vQy1+glpWhPinEb+VywayFf/dx37nBlePpz9FygTqILb/9i6/dyDXjH2S2OD3Km2vnCgN26xTbIVnIm89y5ukOLPEgurIcN10zneFLOLUaqXEFg6W8XmJgdxSlTsAw="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
